### ISSUE TITLE
"ng g c" is not working

### ISSUE THREAD

**Issue by iMarwan-k** [NativeScript/nativescript-schematics#22]
Hi,

When I try to run the command "ng g c <componenet name>"  I get the following error

`Could not find module "@nativescript/schematics" from "/.../my-mobile-app".`

I did run "npm i -g @nativescript/schematics"  and I can create a project using the command
"ng new --collection=@nativescript/schematics --name=my-mobile-app --shared".

inside the project, I did run "npm i" to install dependencies. but the command still not working for "ng g c <componenet name>"

when I run the command "npm i @nativescript/schematic" in the project the command works

Any thoughts?

Thanks

**Comment by NateVonSmith** [comment]
@iMarwan-k I'm running into the same issue and, after some testing, found that this issue arises after running `tns run ...` script (ios in my case). 

If I generate a new project `ng new --collection=@nativescript/schematics --name=new-app --shared`, (and cd into director) `ng g` commands work fine.. until I run `tns run ios` -- then I get the `Could not find module "@nativescript/schematics" ...` message you noted.

Hope this helps maintainers!

**Comment by developerzzz** [comment]
i am facing same issue 
Could not find module "@nativescript/schematics" from "/.../my-mobile-app".
while doing ng g c

**Comment by sebawita** [comment]
Hi @iMarwan-k, @NateVonSmith, @developerzzz 
Sorry for the late reply.

We've just pushed a new version of the @nativescript/schematics, so hopefully this will fix some of the issues.

Can you share the details about your environment?
os: Windows/Linux/Mac
Node version: `node -v`
Angular CLI version: `ng -v`

I can't reproduce the issue:
Here are the steps I followed:
```bash
npm i -g @nativescript/schematics
npm i -g @angular/cli@6.1.0-beta.0
ng new -c=@nativescript/schematics --name=test1 --shared
cd test1
npm i
ng g c cmp1
tns platform add ios
tns run ios --bundle
ng g c cpm2
```

Can you provide the steps you follow that breaks your project?

**Comment by iMarwan-k** [comment]
Hi @sebawita 

Angular CLI: 6.1.0-beta.0
Node: 8.11.1
OS: darwin x64 Mac
Angular: 6.0.5

I just tried to create a component and still not working without installing @nativescript/schematics in locally in the project

I get the following error

Error: Could not find module "@nativescript/schematics" from ".../src/main/angular".
    at Object.resolve (.../src/main/angular/node_modules/@angular-devkit/core/node/resolve.js:141:11)
    at NodeModulesEngineHost._resolvePackageJson (/.../src/main/angular/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:28:21)
    at NodeModulesEngineHost._resolveCollectionPath (.../src/main/angular/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:69:40)
    at NodeModulesEngineHost.createCollectionDescription (/.../src/main/angular/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:106:27)
    at SchematicEngine._createCollectionDescription (.../src/main/angular/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/engine/engine.js:147:40)
    at SchematicEngine.createCollection (.../src/main/angular/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/engine/engine.js:140:43)
    at Object.getCollection (../src/main/angular/node_modules/@angular/cli/utilities/schematics.js:33:31)
    at GenerateCommand.getOptions (.../src/main/angular/node_modules/@angular/cli/models/schematic-command.js:193:41)
    at GenerateCommand.<anonymous> (/.../src/main/angular/node_modules/@angular/cli/commands/generate.js:38:53)
    at Generator.next (<anonymous>)

**Comment by cvietor** [comment]
i can confirm this issue mentioned by @iMarwan-k:

Angular CLI: 6.1.0-beta.0
Node: 8.11.3
OS: win32 x64
Angular: 6.0.9

1. ng new --collection=@nativescript/schematics --name=my-app-name
2. ng g c random-comp1 <-- works
3. npm i
4. ng g c random-comp2 <-- does not work
5. rm -rf node_modules
6. ng g c random-comp3 <-- works

**Comment by sebawita** [comment]
@iMarwan-k @cvietor can you try:
```bash
npm i --save-dev @nativescript/schematics
```
and then try again to generate a component?

I am going to update the template by tomorrow, to come with working defaults out of the box

**Comment by yatinkapur** [comment]
@sebawita 
I ran into this issue but then after running"npm i -g @nativescript/schematics" solved the problem but created another issue "Could not find an NgModule. Use the skip-import option to skip importing in NgModule." when i run "ng g c layout/stack" inside the src folder of my NativeScript Angular App.

**Comment by biswajitkar01** [comment]
In my case, the following worked.
npm install --save-dev @schematics/angular
npm install --save-dev @nativescript/schematics

Thank you!

**Comment by ogb-daniel** [comment]
IN my case i tried everything but still nothing works....pls help me
Error:An unhandled exception occurred: Cannot find module '@schematics/angular/utility/project'

**Comment by henriquebsb** [comment]
@ogb-daniel  i tried everything too with:
Angular CLI: 10.2.0
Node: 12.19.0
OS: win32 x64
Angular: 10.2.0

When i use Angular: 9.1.0, the command "ng g c <component> --skip-import" has sucessfull, but cant import to the app.module. Have to do manually.

**Comment by ogb-daniel** [comment]
I already gave up on nativescript 😂😂😂

**Comment by henriquebsb** [comment]
@ogb-daniel ^^ Did u have others problems with framework? 
i was testing and this is the stable package for use ng generate component

"dependencies": {
    "@angular/animations": "~9.1.0",
    "@angular/common": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/core": "~9.1.0",
    "@angular/forms": "~9.1.0",
    "@angular/platform-browser": "~9.1.0",
    "@angular/platform-browser-dynamic": "~9.1.0",
    "@angular/router": "~9.1.0",
    "@nativescript/angular": "~9.0.0",
    "@nativescript/theme": "~2.3.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.5.0",
    "tns-core-modules": "~6.5.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular/cli": "^9.1.12",
    "@angular/compiler-cli": "~9.1.0",
    "@nativescript/schematics": "^9.0.0",
    "@ngtools/webpack": "~9.1.0",
    "nativescript-dev-webpack": "~1.5.0",
    "tns-platform-declarations": "~6.5.0",
    "typescript": "~3.8.3"
  }

**Comment by ogb-daniel** [comment]
Nah.....bro I switched to react native immediately and its wonderful

**Comment by EsbenKS** [comment]
This is still an issue with new installations in 2020. Just installed on a brand new instance of Windows 10

Too bad is does not "just run out of the box". It's pretty hard to convince co workers to switch to NativeScript with Angular, when we use 1 - 2 working days, just getting a simple tutorial to run..  Too much idle time... We may have to use another framework, just because of this hassle. :-(

**Comment by Lukas-Ertl** [comment]
I created a new empty nativescript projekt and tried every answer here and it still does not work :/
**An unhandled exception occurred: Cannot find module '@schematics/angular/utility/config'**

I really like the idea of nativescript but if i can't even get the cli to work ... :/
